cd "c:/Users/843530433/Desktop/SVN-Project/RT1000/Software/Embedded/1.Hello World/kendryte_uart-interrupt-standalone/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET APPDATA=C:\Users\843530433\AppData\Roaming
SET asl.log=Destination=file
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=DESKTOP-3900Q0S
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SET FPS_BROWSER_USER_PROFILE_STRING=Default
SET HOME=C:\SPB_Data
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\843530433
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=C:\Program Files\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=C:\Program Files\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=C:\Program Files\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\843530~1\AppData\Local\Temp\KendryteIDE_Cache\12348_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LOCALAPPDATA=C:\Users\843530433\AppData\Local
SET LOGONSERVER=\\DESKTOP-3900Q0S
SET MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\Foxit PDF Reader\plugins\
SET NUMBER_OF_PROCESSORS=4
SET OneDrive=E:\OneDrive - Work
SET OneDriveCommercial=E:\OneDrive - Work
SET OS=Windows_NT
SET Path=c:\Program Files\KendryteIDE\bin;C:\Program Files\KendryteIDE\LocalPackage\toolchain\bin;C:\Program Files\KendryteIDE\LocalPackage\cmake\bin;C:\Program Files\KendryteIDE\LocalPackage\jlink;C:\Program Files\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=9e09
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET SYSTEM_TEMP=C:\Users\843530~1\AppData\Local\Temp
SET TEMP=C:\Users\843530~1\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\843530~1\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\843530~1\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=AzureAD
SET USERDOMAIN_ROAMINGPROFILE=AzureAD
SET USERNAME=843530433
SET USERPROFILE=C:\Users\843530433
SET VSCODE_CWD=C:\WINDOWS\System32
SET VSCODE_IPC_HOOK=\\.\pipe\856205e65eb12c85885c97edf69650ec-1.34.1-beta-main-sock
SET VSCODE_LOGS=C:\Program Files\KendryteIDE\UserData\latest\user-data\logs\20210915T152811
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"C:\\Program Files\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"C:\\Program Files\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"C:\\Program Files\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"C:\\Program Files\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=C:\Program Files\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=C:\Program Files\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=13028
SET VSCODE_PORTABLE=C:\Program Files\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET WXDRIVE_START_ARGS=--wxdrive-setting=0 --disable-gpu --disable-software-rasterizer --enable-features=NetworkServiceInProcess
SET ZES_ENABLE_SYSMAN=1
SET PYTHONHOME=C:/Program Files/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=C:/Program Files/KendryteIDE/LocalPackage/python2library;C:/Program Files/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"C:/Program Files/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build "c:/Users/843530433/Desktop/SVN-Project/RT1000/Software/Embedded/1.Hello World/kendryte_uart-interrupt-standalone/build" -- -j 3